name: Auto deploy Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set YML
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION_DEV_YML }}" | base64 --decode > src/main/resources/application-dev.yml
        find src

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Debugging Environment Variables
      run: |
        echo "ECR_REGISTRY=$ECR_REGISTRY"
        echo "ECR_REPOSITORY=sportslight"
        echo "IMAGE_TAG=latest"

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sportslight
        IMAGE_TAG: latest
      run: |
        docker buildx build --platform=linux/amd64 \
          --build-arg JAR_FILE=build/libs/*.jar \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --build-arg DATABASE_USER=${{ secrets.DATABASE_USER }} \
          --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          --build-arg S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
          --build-arg S3_BUCKET_ACCESS_KEY=${{ secrets.S3_BUCKET_ACCESS_KEY }} \
          --build-arg S3_BUCKET_SECRET_KEY=${{ secrets.S3_BUCKET_SECRET_KEY }} \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD_HH-mm-ss
        utcOffset: "+09:00"

    - name: Prepare Docker Compose file
      run: |
        cp docker-compose.yml deploy/
        sed -i "s|\${ECR_REGISTRY}|${{ steps.login-ecr.outputs.registry }}|g" deploy/docker-compose.yml
        sed -i "s|\${ECR_REPOSITORY}|sportslight|g" deploy/docker-compose.yml
        sed -i "s|\${IMAGE_TAG}|latest|g" deploy/docker-compose.yml


    - name: Generate deployment package
      run: |
        mkdir -p deploy
        cp -r docker-compose.yml deploy/docker-compose.yml
        cd deploy && zip -r deploy.zip .

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APP_NAME }}
        environment_name: ${{ secrets.EB_ENV_NAME }}
        version_label: earth-docker-${{steps.current-time.outputs.formattedTime}}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy/deploy.zip
        wait_for_environment_recovery: 150
